# Generated by Django 5.0.2 on 2024-03-13 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_remove_item_used_item_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='spent',
        ),
    ]
