# Generated by Django 5.0.2 on 2024-03-13 22:06

import django.db.models.deletion
import django.db.models.functions.datetime
import item.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_remove_item_spent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('image', models.ImageField(default='itemDefault.jpg', upload_to=item.models.upload_to_item_list)),
                ('date', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='amount',
        ),
        migrations.AddField(
            model_name='item',
            name='list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='item.item_list'),
            preserve_default=False,
        ),
    ]
