# Generated by Django 5.0.2 on 2024-03-13 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_item_list_remove_item_amount_item_list'),
        ('job', '0008_alter_job_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='job',
            field=models.OneToOneField(default=4, on_delete=django.db.models.deletion.CASCADE, to='job.job'),
            preserve_default=False,
        ),
    ]
