# Generated by Django 5.0.2 on 2024-03-31 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_item_job'),
        ('job', '0008_alter_job_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job'),
        ),
    ]
