# Generated by Django 5.2.4 on 2025-07-12 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_extraexpense_image_extraincome_image_and_more'),
        ('item', '0007_item_list_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_list',
            name='provider',
        ),
        migrations.AddField(
            model_name='item_list',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_list', to='business.business'),
        ),
    ]
