# Generated by Django 5.2.4 on 2025-07-19 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_remove_item_list_provider_item_list_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='testDefault.jpg', upload_to='test_images/')),
            ],
        ),
    ]
