# Generated by Django 5.2.4 on 2025-07-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_testmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='image',
            field=models.ImageField(default='testDefault.jpg', upload_to='test/'),
        ),
    ]
