# Generated by Django 5.2.4 on 2025-08-23 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_alter_item_price_alter_item_list_price'),
        ('job', '0023_remove_spent_amount_spent_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='job.job'),
        ),
    ]
