# Generated by Django 5.2.4 on 2026-04-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_alter_item_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item_list',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
