# Generated by Django 5.2.4 on 2025-07-04 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('client', '0002_alter_client_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='business_client', to='business.business'),
            preserve_default=False,
        ),
    ]
