# Generated by Django 5.2.4 on 2025-07-14 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(default='no last name saved', max_length=80),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
