# Generated by Django 5.2.4 on 2025-08-10 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_alter_extraexpense_image_alter_extraincome_image'),
        ('client', '0004_alter_client_last_name_alter_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='business.business'),
        ),
    ]
