# Generated by Django 5.2.4 on 2025-08-23 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_client_created_at_client_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address2',
            field=models.CharField(default='no extra address saved', max_length=50),
        ),
    ]
