# Generated by Django 5.2.4 on 2025-08-24 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_paymentmethodtype_businesspaymentmethod'),
        ('client', '0007_client_address2'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='preferred_payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_clients', to='business.businesspaymentmethod'),
        ),
    ]
