# Generated by Django 5.2.4 on 2026-05-21 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_client_preferred_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(default='no phone saved', max_length=20),
        ),
    ]
