# Generated by Django 5.2.4 on 2025-07-09 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_expenses', to='business.business')),
            ],
            options={
                'verbose_name': 'Extra Expense',
                'verbose_name_plural': 'Extra Expenses',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ExtraIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_incomes', to='business.business')),
            ],
            options={
                'verbose_name': 'Extra Income',
                'verbose_name_plural': 'Extra Incomes',
                'ordering': ['-date'],
            },
        ),
    ]
