# Generated by Django 5.2.4 on 2025-07-10 01:34

import business.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_extraexpense_extraincome'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraexpense',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=business.models.upload_to_extra_expense),
        ),
        migrations.AddField(
            model_name='extraincome',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=business.models.upload_to_extra_income),
        ),
        migrations.AlterField(
            model_name='extraincome',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_income', to='business.business'),
        ),
    ]
