# Generated by Django 5.2.4 on 2025-07-14 02:05

import business.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='code',
            field=models.CharField(default=business.models.invitationCode, max_length=50, unique=True),
        ),
    ]
