# Generated by Django 5.2.4 on 2025-07-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_invitation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
