# Generated by Django 5.2.4 on 2025-07-31 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_extraexpense_category_extraexpense_tax_deductible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraexpense',
            name='category',
            field=models.CharField(choices=[('office_supplies', 'Office Supplies'), ('utilities', 'Utilities'), ('marketing', 'Marketing'), ('other', 'Other'), ('travel', 'Travel'), ('maintenance', 'Maintenance'), ('salaries', 'Salaries'), ('taxes', 'Taxes'), ('medical_insurance', 'Medical Insurance'), ('insurance', 'Insurance'), ('equipment', 'Equipment'), ('software', 'Software'), ('legal_fees', 'Legal Fees'), ('training', 'Training'), ('research', 'Research'), ('licenses', 'Licenses'), ('repairs', 'Repairs'), ('shipping', 'Shipping'), ('warranty', 'Warranty'), ('fines', 'Fines'), ('commissions', 'Commissions'), ('bank_fees', 'Bank Fees'), ('interest', 'Interest'), ('fuel', 'Fuel'), ('meals', 'Meals')], default='other', max_length=50),
        ),
    ]
