# Generated by Django 5.2.4 on 2025-08-02 21:14

import business.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_alter_extraexpense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraexpense',
            name='image',
            field=models.ImageField(default='expenseDefault.jpg', upload_to=business.models.upload_to_extra_expense),
        ),
        migrations.AlterField(
            model_name='extraincome',
            name='image',
            field=models.ImageField(default='incomeDefault.jpg', upload_to=business.models.upload_to_extra_income),
        ),
    ]
