# Generated by Django 5.2.4 on 2025-08-24 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_business_address2_alter_extraexpense_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('requires_email', models.BooleanField(default=False)),
                ('requires_phone', models.BooleanField(default=False)),
                ('requires_username', models.BooleanField(default=False)),
                ('supports_deep_links', models.BooleanField(default=False)),
                ('deep_link_pattern', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('account_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('account_username', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='business.business')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.paymentmethodtype')),
            ],
            options={
                'unique_together': {('business', 'payment_type')},
            },
        ),
    ]
