# Generated by Django 5.0.2 on 2024-06-11 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='provider',
        ),
    ]
