# Generated by Django 5.0.2 on 2024-06-11 19:30

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_profile_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='business_logo',
            field=models.ImageField(default='logoDefault.png', upload_to=user.models.upload_logo_to, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='profile',
            name='business_name',
            field=models.CharField(default='Business Name', max_length=150),
        ),
    ]
