# Generated by Django 5.2.4 on 2025-07-18 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_registrationcode_dateend_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='business_logo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='business_name',
        ),
    ]
