# Generated by Django 5.2.4 on 2025-07-31 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_profile_business_logo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationcode',
            old_name='dateStart',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='registrationcode',
            old_name='dateEnd',
            new_name='used',
        ),
    ]
