# Generated by Django 5.2.4 on 2025-07-31 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_datestart_registrationcode_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationcode',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
