# Generated by Django 5.2.4 on 2026-04-19 22:06

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_profile_address_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationcode',
            name='code',
            field=models.CharField(default=user.models.generarHash, max_length=6, unique=True),
        ),
    ]
