# Generated by Django 5.0.2 on 2024-02-28 20:31

import django.db.models.deletion
import django.db.models.functions.datetime
import job.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to=job.models.upload_to_job)),
                ('date', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
        ),
        migrations.CreateModel(
            name='Spent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to=job.models.upload_to_spent)),
                ('date', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
            ],
        ),
    ]
