# Generated by Django 5.0.2 on 2024-02-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='amount',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spent',
            name='amount',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
