# Generated by Django 5.0.2 on 2024-02-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_job_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='amount',
            new_name='price',
        ),
        migrations.AddField(
            model_name='job',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('new', 'NEW'), ('active', 'ACTIVE'), ('finished', 'FINISHED')], default='new', max_length=15),
            preserve_default=False,
        ),
    ]
