# Generated by Django 5.0.2 on 2024-02-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_rename_amount_job_price_job_closed_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('new', 'NEW'), ('active', 'ACTIVE'), ('finished', 'FINISHED')], default='new', max_length=15),
        ),
    ]
