# Generated by Django 5.0.2 on 2024-02-29 01:49

import job.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spent',
            name='image',
            field=models.ImageField(default='spents/spentDefault.jpg', upload_to=job.models.upload_to_spent),
        ),
    ]
