# Generated by Django 5.0.2 on 2024-03-02 00:49

import job.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_spent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(default='jobDefault.jpg', upload_to=job.models.upload_to_job),
        ),
        migrations.AlterField(
            model_name='spent',
            name='image',
            field=models.ImageField(default='spentDefault.jpg', upload_to=job.models.upload_to_spent),
        ),
    ]
