# Generated by Django 5.0.2 on 2024-05-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_invoice_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(editable=False, max_length=7, unique=True),
        ),
    ]
