# Generated by Django 5.0.2 on 2024-06-12 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_provider'),
        ('job', '0013_alter_job_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='bill_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='client.client'),
        ),
    ]
