# Generated by Django 5.0.2 on 2024-06-12 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_alter_invoice_bill_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='job.invoice'),
        ),
    ]
