# Generated by Django 5.2.4 on 2025-07-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0018_job_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='price',
            field=models.FloatField(),
        ),
    ]
