# Generated by Django 5.2.4 on 2025-08-23 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0021_rename_date_job_created_at_job_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='address2',
            field=models.CharField(default='no extra address saved', max_length=50),
        ),
    ]
