# Generated by Django 5.2.4 on 2025-08-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0022_job_address2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spent',
            name='amount',
        ),
        migrations.AddField(
            model_name='spent',
            name='price',
            field=models.FloatField(default=45),
            preserve_default=False,
        ),
    ]
