# Generated by Django 5.2.4 on 2025-08-24 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_paymentmethodtype_businesspaymentmethod'),
        ('job', '0023_remove_spent_amount_spent_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='payment_method_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_jobs', to='business.businesspaymentmethod'),
        ),
        migrations.AddField(
            model_name='job',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=20),
        ),
    ]
