# Generated by Django 5.2.4 on 2026-04-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0024_job_payment_method_used_job_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='spent',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
